### ISSUE TITLE
Roadmap for v3

### ISSUE THREAD

**Issue by cesasol** [nuxt-community/nuxtent-module#182]
This is a list of goals to meet before releasing a stable 3 version:

- [ ] Improve the documentation and at least a spanish translation
- [ ] Windows compatible (Help needed)
- [ ] Be zeroconf and extendible through it's own api and exposing the markdown parser
- [ ] Allow default attributes to be set on the frontmatter ej. title
- [ ] Real async modules (this affects ssr more than a static build)
- [ ] Fully integrate with the new features nuxt2.0 and node 11
- [ ] Debugable configuration
- [ ] Better error reporting
- [ ] Improve the template with optional addons as examples
- [ ] Document the code in order to simplify contributions and future development
- [ ] Support multiple file types (json, yaml, markdown, html and pug)
- [ ] Integrate the api configuration with nuxt itself while keeping it configurable
- [x] Expose $content helper and it's constant like api endpoint through all of vue
- [ ] Keep the main features from nuxtdown:
  - [x] Breadcrubms
  - [ ] Automatic table of content (TOC)
  - [x] Isolated and global configurations
  - [x] Allow for nested content and index files

The following are the features that would be nice to have but are left for a future release 3.x

- [ ] Vuex integration
- [ ] Improve on SSR memory usage
- [ ] Use sqlite for the content

All of the previous features are open to discussion and may be expanded to fit more use cases.

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtent-module/issues/c141">#c141</a>)</em></sub></div>

**Comment by renestalder** [comment]
@cesasol Just want to check in. Is there a plan of action for continuous development? Or do you recommend alternatives to nuxtent?

I really love how this module works and I would even help you to develop it further. I currently use a fork of this project, but all the forks state that the "maybe" get merged some day. You especially did quite some changes on the development branch, so I wondering, when these get released and the "don't use in production" line removed.

**Comment by joostdecock** [comment]
Guys, I should perhaps clarify my (lack of) involvement in this project. As you may or may not know, I'm using nuxtdown in production on freesewing.org, and that's how I got involved in the first place.

However, I've been working on a new frontend built on React/Gastby, and as soon as it's ready I will no longer have a stake in Nuxtent.

That being said, I think this is a very useful module, and you guys are doing great work :1st_place_medal:

**Comment by manniL** [comment]
@joostdecock I'd love to hear the reasons why you switched over ☺️

**Comment by joostdecock** [comment]
> @joostdecock I'd love to hear the reasons why you switched over ☺️

We currently [deploy about 2700 pages](https://app.netlify.com/sites/fs-beta/deploys/5c68391eaef3dc0008d7fdfc), and the vast majority of those are just embellished markdown.

We have a ton of documentation, we have blog posts, showcases from the community, 5 different languages, and other things that are more *website* than *app*.

For our needs, Gatbsy and the ecosystem around it felt like a better match.

**Comment by renestalder** [comment]
Maybe a bit off-topic here but keep [Gridsome](https://gridsome.org/) on the radar if you look for something similar like Gatsby for Vue.js.

That's also my next alternative after Nuxtent (maybe will desperately fork @joostdecock's Nuxtdown branch and try to fix some things but if this doesn't work, probably make the switch).

**Comment by manniL** [comment]
@renestalder We really want to improve the "static" part of nuxt, especially when it comes to easier integrations.

I'm pretty sure that Nuxtent and the full-static mode are two points to start with but not the end of the improvements.

**Comment by manniL** [comment]
@joostdecock Interesting! Thanks for the insights ☺️

**Comment by renestalder** [comment]
@manniL Thanks for the info. I somehow just would wish that the patches that are applied on one of the development branches now (especially for Nuxt 2.3 compatibility) would go into a patch release. I see that some refactoring is going on but I wonder if that is required for releasing some patches at this moment. It doesn't make much sense for me to now dig into the code to apply the patches for myself in my projects and at the same time, I don't want to hook in the development branch into my projects as there is a clear warning that nobody should use that in production.

**Comment by cesasol** [comment]
@renestalder I use it in production for many sites. It's just that I haven't had the time to keep documenting all that is going on, there is some progress to document and refactor all the code to make possible what @joostdecock does but with Nuxt and async components.

But with my team we are looking to keep maintaining this as well as possible but is not really our highest priority.

**Comment by cesasol** [comment]
@manniL I'm looking to keep track of [this](https://github.com/nuxt/rfcs/issues/22) and add some ideas from my experience with nuxt.

**Comment by chadananda** [comment]
It would be pretty great to get robust data API plugins into Nuxt -- and dispense entirely with the need for Nuxtent.

**Comment by callumflack** [comment]
I've been using Nuxtent for a while, since @alidcastano started it. At the moment, I don't like that I can't use it with the ongoing progress of Nuxt v2. 

I've also seen the rise of MDX. The React folk seem to be taking the idea of "markdown for the component era" to a new level within Storybook or @jxnblk's [MDX Blocks](https://github.com/jxnblk/mdx-blocks) ideas. Although there is [an example of MDX within Vue](https://github.com/mdx-js/mdx/issues/238#issuecomment-486907152) (albeit it currently fails), I can't help but think this is a blindspot within Vue.

The priorities of Nuxtent seem to have more of a focus on extending markdown as a publishing tool (eg. breadcrumbs / TOC) rather than creative component integration. 

In light of MDX, what are folk's thoughts for the vision of Nuxtent?

**Comment by cesasol** [comment]
It looks that it has a different approach to a similar end, at work we use markdown components (.comp.md files) with custom vue components for each site we build, so I think nuxtent already has and had for quite some time the ability to compose complex page structures with layout and presentational components. However if you point out something that could be missing from nuxtent I will be glad to hear it.

As for future compatibility yesterday I [published](https://www.npmjs.com/package/@dinamomx/nuxtent) a ts rewrite with fixes, some improvements to  and implements all the features from nuxtdown plus some that where requested along the way like excerpts. However I'm pretty much the only one writing code for nuxtent right now, and even with the support from my work (time) there is so much I can do, that means that at least from my part nuxtent will be maintained for the foreseeable future but do not expect that I keep up with nuxt team's rhythm and their many breaking changes on their internal api.

As a showcase of this version working with some  we built quite a [complex site](http://www.infinitipedregalinterlomas.com/) on using nuxtent and it works with 2.3.x up until 2.6.x We are using YAML, JSON, plain markdown, markdown with some extensions and markdown components for different parts of the site.

**Comment by cesasol** [comment]
@chadananda I don't think a fully robust api is the way to go, as far as the (little) feedback that this module has gotten most people use it with the generate option, so i don't think a fully sql like query api would bee appropriate but I do think that it can be better with thinks like paginating and custom ordering.

**Comment by callumflack** [comment]
@cesasol huge! Going to test your new commits in [my business site repo](https://github.com/callumflack/callum-flack-design) this coming week.

I don't feel my JS isn't good enough to help out. Else I would offer. I'm grateful that you're doing this.

**Comment by cesasol** [comment]
@callumflack Testing is a great way to collaborate!

**Comment by callumflack** [comment]
@cesasol then I shall test shortly, this week ;)

**Comment by callumflack** [comment]
@cesasol so sorry but how would I use your latest commits to test?

In my naive attempt at adding the commit to my package.json, yarn forces me to select a release version:

![image](https://user-images.githubusercontent.com/749885/57053183-bf98c100-6ccf-11e9-850c-af7bb83dc997.png)

**Comment by cesasol** [comment]
You could use the @dinamomx/nuxtent package, is published on npm and currently has the latest commit.
